routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Route::get('/home,/', 'HomeController@home')->name('home');

// Main page
Route::get('/', 'HomeController@home')->name('home');
// Routes for UserController
Route::resource('/user', 'UserController');
// Routes for PostController
Route::resource('/post', 'PostController');
// Routes for TagController
Route::resource('/tag', 'TagController');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    // a tag can belongs to many posts
    public function posts()
    {
        return $this->belongsToMany(Post::class)->withTimestamps();
    }

    // a tag must be created by one and only one user
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // function to find a tag
    public function findTag($tagId)
    {
        return self::find($tagId);
    }

    // This function will store the data in DB
    public function storeTag($tagName)
    {
        $tag = new Tag();
        $tag->name    = $tagName;
        $tag->user_id = auth()->id();
        $tag->save();
    }

    //  This function will delete the tag
    public function destroyTag($tagId)
    {
        $tag = self::findTag($tagId);
        $tag->delete();
        $tag->posts()->detach();
    }

    // This function will update the tag
    public function updateTag($tagName, $tagId)
    {
        $tag = self::findTag($tagId);
        $tag->name    = $tagName;
        $tag->user_id = auth()->id();
        $tag->update();
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTag;
use App\Http\Requests\UpdateTag;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    private $tags;

    public function __construct(Tag $tag)
    {
        // initializing the private variable of the calls to communicate with model
        $this->tags = $tag ;
        // applying auth middleware
        $this->middleware("auth");
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // fetching all tags to show on widget box
        $tags  = Tag::all();
//        $tags  = array();

        return view("tags.index",compact("tags"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        return view("tags.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTag $request)
    {
       $this->tags->storeTag($request->name);
       return redirect()->back()->with("success","Tag created Successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($tagId)
    {
        // This function will fetch all posts where tag id = $id
        $tag        = $this->tags->findTag($tagId);
        // fetching all posts associate with the tag
        $postsByTag = $tag->posts()->orderBy("id","desc")->paginate(2);
        // fetching all tags to show on widget box
        $tags  = Tag::all();
        return view("tags.show-post-by-tags",compact("postsByTag","tags"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($tagId)
    {
        // fetching single tag
        $tag  = $this->tags->findTag($tagId);
        // fetching all tags
        $tags = Tag::all();
        return view("tags.edit",compact("tag","tags"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTag $request, $id)
    {
        $this->tags->updateTag($request->name,$id);
        return redirect()->route("tag.index")->with("success","Tag Updated Successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($tagId)
    {
       $this->tags->destroyTag($tagId);
    }
}

resources/views/tags/edit.blade.php
{{-- This page is responsible to create posts -}}

{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This section is for special css files--}}
@section("styles")
    <link rel="stylesheet" type="text/css" href="{{asset("assets/frontend/plugins/select2/css/select2.min.css")}}">
@endsection

{{-- This section is for page title--}}
@section("title")
    Create Tag
@endsection

@section("main-container")
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-sm-12">
                @if(Session::has('success'))
                    <div class="alert alert-success mt-1">{{Session::get('success')}}</div>
                @endif
                <h1 class="my-4">Edit The Tag</h1>
                <form action="{{ route("tag.update",$tag->id) }}" method="post" autocomplete="off">
                    {{ method_field("PUT") }}
                    {{ csrf_field() }}
                    <div class="form-group mb-2">
                        <label for="">Tag Name : </label>
                        <input type="text" class="form-control" id="" placeholder="i.e Jquery" name="name" value="{{ $tag->name }}">
                        @if ($errors->has('name'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success float-right mb-2">Update</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h1> Tags List</h1>
                <table class="table table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Created On</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($tags as $tag)
                        <tr id="tag{{$tag->id}}">
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $tag->name }}</td>
                            <td>{{ $tag->created_at->toFormattedDateString() }}</td>
                            <td>
                                <a class='btn btn-secondary' href='{{ route("tag.edit",$tag->id) }}' data-id="{{$tag->id}}">Edit</a>
                                <a class='deleteTagButton btn btn-dark text-white' data-id="{{$tag->id}}">Delete</a>
                            </td>
                        </tr>
                    @empty
                        <h2 class="text-center text-danger">No Tags found</h2>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

{{-- This section is for special scripts--}}
@section("script")
    <script src="{{asset("assets/frontend/plugins/select2/js/select2.min.js")}}"></script>
    <script>
        $('.js-example-basic-multiple').select2({
            placeholder: 'Assign Users'
        });
    </script>
@endsection

resources/views/tags/index.blade.php
{{-- This page is responsible to create posts -}}

{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This section is for special css files--}}
@section("styles")
    <link rel="stylesheet" type="text/css" href="{{asset("assets/frontend/plugins/select2/css/select2.min.css")}}">
@endsection

{{-- This section is for page title--}}
@section("title")
    Create Tag
@endsection

@section("main-container")
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-sm-12">
                @if(Session::has('success'))
                    <div class="alert alert-success mt-1">{{Session::get('success')}}</div>
                @endif
                <h1 class="my-4">Create A Tag</h1>
                <form action="{{ route("tag.store") }}" method="post" autocomplete="off">
                    {{ csrf_field() }}
                    <div class="form-group mb-2">
                        <label for="">Tag Name : </label>
                        <input type="text" class="form-control" id="" placeholder="i.e Jquery" name="name">
                        @if ($errors->has('name'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success float-right mb-2">Create</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h1> Tags List</h1>
                <table class="table table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Created On</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse($tags as $tag)
                            <tr id="tag{{$tag->id}}">
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $tag->name }}</td>
                                <td>{{ $tag->created_at->toFormattedDateString() }}</td>
                                <td>
                                    <a class='btn btn-secondary' href='{{ route("tag.edit",$tag->id) }}' data-id="{{$tag->id}}">Edit</a>
                                    <a class='deleteTagButton btn btn-dark text-white' data-id="{{$tag->id}}">Delete</a>
                                </td>
                            </tr>
                        @empty
                               <h2 class="text-center text-danger">No Tags found</h2>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

{{-- This section is for special scripts--}}
@section("script")
    <script src="{{asset("assets/frontend/plugins/select2/js/select2.min.js")}}"></script>
    <script>
        $('.js-example-basic-multiple').select2({
            placeholder: 'Assign Users'
        });
    </script>
@endsection

resources/views/tags/show-post-by-tags.blade.php
<?php
// an array of colors
$badgeColors = ["primary", "secondary", "success", "danger", "warning", "info", "dark"]
?>
{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This page is responsible to show posts on the home page--}}

{{-- This section is for page title--}}
@section("title")
    Post By Tags
@endsection

@section("main-container")
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="{{ Auth::check() ? "col-md-8" : "col-md-12"}}">

            {{--<h1 class="my-4">Page Heading--}}
            {{--<small>Secondary Text</small>--}}
            {{--</h1>--}}

            <!-- Blog Post -->
                @foreach($postsByTag as $post)
                    <div class="card mb-4 mt-4">
                        {{--if the user is logged in then the display size of image will be 750x300
                            else it will be 1050x300--}}
                        {{--http://placehold.it/{{ Auth::check() ? "750x300" : "1050x300--}}
                        <img class="card-img-top" src="{{ asset("assets/frontend/images/post/".$post->image) }}"
                             alt="Card image cap" width="300" height="350">
                        <div class="card-body">
                            <h2 class="card-title">{{ $post->title }}</h2>
                            {{-- This loop will fetch all the tags linked with the post--}}
                            @foreach($post->tags as $tag)
                                {{-- The badgeColors array will work from index 0 to the size of array -1 --}}
                                <span class="badge badge-pill badge-{{ $badgeColors[mt_rand(0,sizeof($badgeColors)-1)] }}">{{ $tag->name }}</span>
                            @endforeach
                            {{-- This will only be shown if the user is logged in--}}
                            @if(auth::check())
                                <p class="card-text">{{ $post->description }}</p>
                            @endif
                            {{-- The following condition will check if the user is looged in then the button
                            will take user to the description page else it take the user to the login page--}}
                            <a href="{{ auth::check() ? "/post/$post->id": route("login") }}" class="btn btn-primary">Read More &rarr;</a>
                            @auth
                                @if(auth()->user()->is_admin == 1)
                                    <a class='btn btn-warning pull-right text-white' href='{{ route("post.edit",$post->id) }}' data-id="{{$post->id}}">Edit</a>
                                    <a class='deletePostButton btn btn-danger pull-right text-white' data-id="{{$post->id}}">Delete</a>
                                @endif
                            @endauth
                        </div>
                        <div class="card-footer text-muted">
                            Posted on {{ $post->created_at->toFormattedDateString() }} by
                            <a href="#">{{ ucfirst($post->user->name) }}</a>
                        </div>
                    </div>
                @endforeach

                {{--<!-- Pagination -->--}}
                <div class="pagination justify-content-center mb-4">
                    {{ $postsByTag->links() }}
                </div>

            </div>

            <!-- Sidebar Widgets Column -->
            {{-- Note this coloumn will only be shown if the user is logged in --}}
            <div class="col-md-4 {{ Auth::check() ? "" : "d-none"}}">

                <!-- Search Widget -->
            {{--<div class="card my-4">--}}
            {{--<h5 class="card-header">Search</h5>--}}
            {{--<div class="card-body">--}}
            {{--<div class="input-group">--}}
            {{--<input type="text" class="form-control" placeholder="Search for...">--}}
            {{--<span class="input-group-btn">--}}
            {{--<button class="btn btn-secondary" type="button">Go!</button>--}}
            {{--</span>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}

                {{-- Including tags widget--}}
            @include("includes.frontend.tags-widget")

                <!-- Side Widget -->
                {{--<div class="card my-4">--}}
                {{--<h5 class="card-header">Side Widget</h5>--}}
                {{--<div class="card-body">--}}
                {{--You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!--}}
                {{--</div>--}}
                {{--</div>--}}

            </div>
        </div>
    </div>
@endsection