routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Route::get('/home,/', 'HomeController@home')->name('home');

// Main page
Route::get('/', 'HomeController@home')->name('home');
// Routes for UserController
Route::resource('/user', 'UserController');
// Routes for PostController
Route::resource('/post', 'PostController');
// Routes for TagController
Route::resource('/tag', 'TagController');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use phpDocumentor\Reflection\Types\Self_;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title','description','image'
    ];

    // post must be created by one and only one user
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // post should have many tags
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    // function to find a post
    public function findpost($postId)
    {
        return self::find($postId);
    }

    // This function will create post
    public function StorePost($postData)
    {
        $post               = new Post()                            ;
        $post->title        = $postData->title                      ;
        $post->user_id      = auth()->id()                          ;
        $post->description  = $postData->description                ;
        if ($postData->hasFile('image'))
        {
            $file           = $postData->file('image')              ;
            $imageName      = time().$file->getClientOriginalName() ;
            $file->move('assets/frontend/images/post', $imageName)  ;
        }
        $post->image        = $imageName                            ;
        $post->save()                                               ;
        return $post                                                ;
    }

    // This function will sync the tags with post
    public function syncTags($tags, $postId)
    {
        $post = self::findpost($postId);
        $post->tags()->sync($tags);
    }

    // This function will delete the post
    public function deletePost($postId)
    {
        $post = self::findpost($postId);
        // unlinking the image
        if (file_exists("../public/assets/frontend/images/post/$post->image")) {
            unlink("../public/assets/frontend/images/post/$post->image");
            echo 'Deleted old image';
        }
        else {
            echo 'Image file does not exist';
        }
        $post->delete();
        // detaching the tags associated to the post
        $post->tags()->detach();
    }

    // This function will update the Post
    public function updatePost($request, $id)
    {
//        dd($request->all());
        $post = self::findpost($id);
        $post->title    = $request->title;
        $post->user_id = auth()->id();
        $post->description  = $request->description                 ;
        // if the request has the image then it will add image to db else it will store the old name
        // of the image in the db
        if ($request->hasFile('image'))
        {
            $file           = $request->file('image')               ;
            $imageName      = time().$file->getClientOriginalName() ;
            $file->move('assets/frontend/images/post', $imageName)  ;
        }
        else
        {
            $imageName = $post->image                               ;
        }

        $post->image        = $imageName                            ;
        $post->update();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePost;
use App\Http\Requests\UpdatePost;
use App\Models\Post;
use App\Models\Tag;
use Illuminate\Http\Request;

class PostController extends Controller
{
    private $posts;

    public function __construct(Post $post)
    {
        // initializing the private variable of the calls to communicate with model
        $this->posts = $post ;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // fetching all tags to show on widget box
        $tags  = Tag::all();

        return view("posts.create",compact("tags"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request)
    {
//        dd($request->all());
        $post = $this->posts->StorePost($request);
        $this->posts->syncTags($request->tags,$post->id);
        return redirect()->back()->with("success","Post Created Successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($postId)
    {
        // This function will fetch post where post id = $postId
        $post        = $this->posts->findpost($postId);
        // fetching all tags to show on widget box
        $tags  = Tag::all();
        return view("posts.show",compact("post","tags"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        $tags  = Tag::all();
        return view("posts.edit",compact("post","tags"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePost $request, $id)
    {
        $this->posts->updatePost($request,$id);
        // this function will look for the tags and or replace the values in db using sync method
        $this->posts->syncTags($request->tags,$id);
        return redirect()->route("home")->with("success","Post Updated Successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($postId)
    {
        $this->posts->deletePost($postId);
    }
}

resources/views/posts/create.blade.php
{{-- This page is responsible to create posts -}}

{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This section is for special css files--}}
@section("styles")
    <link rel="stylesheet" type="text/css" href="{{asset("assets/frontend/plugins/select2/css/select2.min.css")}}">
@endsection

{{-- This section is for page title--}}
@section("title")
    Create Post
@endsection

@section("main-container")
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-12">
                @if(Session::has('success'))
                    <div class="alert alert-success mt-1">{{Session::get('success')}}</div>
                @endif
             <h1 class="my-4">Create A post</h1>
                <form action="{{ route("post.store") }}" method="post" enctype="multipart/form-data" autocomplete="off">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Post Title</label>
                        <input type="text" class="form-control" id="" placeholder="i.e Hello World" name="title"
                        value="{{old("title")}}">
                        @if ($errors->has('title'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Post Description</label>
                        <textarea class="form-control" id="" rows="3" name="description" >{{ old("description") }}</textarea>
                        @if ($errors->has('description'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <div for="exampleFormControlSelect1">Select Tags</div>

                        {{--<select class="form-control js-example-basic-multiple"--}}
                        {{--multiple style="width: 100%" name="tags[]">--}}
                        {{--<option value="" hidden></option>--}}
                        @foreach($tags as $tag)
                            <label class="checkbox-inline">
                                <input type="checkbox" value="{{ $tag->id }}" name="tags[]"> {{ $tag->name }}
                            </label>
                            {{--<option value="{{$tag->id}}">{{$tag->name}}</option>--}}
                        @endforeach
                        {{--</select>--}}
                        @if ($errors->has('tags'))
                            <div class="text-danger" role="alert">
                                <strong>{{ $errors->first('tags') }}</strong>
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Post Image</label>
                        <input type="file" class="form-control-file" id="" name="image">
                        @if ($errors->has('image'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success col-sm-2 float-right mb-2">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

{{-- This section is for special scripts--}}
@section("script")
    <script src="{{asset("assets/frontend/plugins/select2/js/select2.min.js")}}"></script>
     <script>
        $('.js-example-basic-multiple').select2({
            placeholder: 'Assign Users'
        });
    </script>
@endsection

resources/views/posts/edit.blade.php
<?php
    //  creating an array of tag id's that are associated with the post
    foreach($post->tags as $tag)
    {
     // array of id
        $tagsArrayId[] = $tag->id;
    }
?>
{{-- This page is responsible to edit posts -}}

{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This section is for special css files--}}
@section("styles")
    <link rel="stylesheet" type="text/css" href="{{asset("assets/frontend/plugins/select2/css/select2.min.css")}}">
@endsection

{{-- This section is for page title--}}
@section("title")
    Edit Post
@endsection

@section("main-container")
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-12">
                <h1 class="my-4">Edit The Post</h1>
                <form action="{{ route("post.update",$post->id) }}" method="post" enctype="multipart/form-data" autocomplete="off">
                    {{ method_field("PUT") }}
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Post Title</label>
                        <input type="text" class="form-control" id="" placeholder="i.e Hello World"
                               value="{{ $post->title }}" name="title">
                        @if ($errors->has('title'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <div for="exampleFormControlSelect1">Select Tags</div>
                            @foreach($tags as $tag)
                            <label class="checkbox-inline">
                                    <input type="checkbox" value="{{ $tag->id }}"
                                           name="tags[]" {{ in_array($tag->id,$tagsArrayId) ? "checked" : "" }} > {{ $tag->name }}
                            </label>
                            @endforeach
                            @if ($errors->has('tags'))
                                <div class="text-danger" role="alert">
                                    <strong>{{ $errors->first('tags') }}</strong>
                                </div>
                            @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Post Description</label>
                        <textarea class="form-control" id="" rows="3" name="description">{{ $post->description }}</textarea>
                        @if ($errors->has('description'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Post Image</label>
                        <input type="file" class="form-control-file" id="" name="image">
                        @if ($errors->has('image'))
                            <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success col-sm-2 float-right mb-2">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

{{-- This section is for special scripts--}}
@section("script")
    <script src="{{asset("assets/frontend/plugins/select2/js/select2.min.js")}}"></script>
    <script>
        $('.js-example-basic-multiple').select2({
            placeholder: 'Assign Users'
        });
    </script>
@endsection

resources/views/posts/index.blade.php
<?php
    // an array of colors
    $badgeColors = ["primary", "secondary", "success", "danger", "warning", "info", "dark"]
?>
{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This page is responsible to show posts on the home page--}}

{{-- This section is for page title--}}
@section("title")
    Home
@endsection

@section("main-container")
    <div class="container">
        @if(Session::has('success'))
            <div class="alert alert-success mt-1">{{Session::get('success')}}</div>
        @endif
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="{{ Auth::check() ? "col-md-8" : "col-md-12"}}">

                {{--<h1 class="my-4">Page Heading--}}
                    {{--<small>Secondary Text</small>--}}
                {{--</h1>--}}

                <!-- Blog Post -->
                 @forelse($posts as $post)
                    <div class="card mb-4 mt-4" id="post{{$post->id}}">
                            {{--if the user is logged in then the display size of image will be 750x300
                                else it will be 1050x300--}}
                             {{--http://placehold.it/{{ Auth::check() ? "750x300" : "1050x300--}}
                            <img class="card-img-top" src="{{ asset("assets/frontend/images/post/".$post->image) }}"
                                 alt="Card image cap" width="300" height="350">
                            <div class="card-body">
                                <h2 class="card-title">{{ $post->title }}</h2>
                                {{-- This will only be shown if the user is logged in--}}
                                @if(auth::check())
                                    {{-- This loop will fetch all the tags linked with the post--}}
                                    @foreach($post->tags as $tag)
                                        {{-- The badgeColors array will work from index 0 to the size of array -1 --}}
                                        <span class="badge badge-pill badge-{{ $badgeColors[mt_rand(0,sizeof($badgeColors)-1)] }}">{{ $tag->name }}</span>
                                    @endforeach
                                @endif
                                {{-- This will only be shown if the user is logged in--}}
                                @if(auth::check())
                                    <p class="card-text">{{ $post->description }}</p>
                                @endif
                                {{-- The following condition will check if the user is looged in then the button
                                will take user to the description page else it take the user to the login page--}}
                                <a href="{{ auth::check() ? "/post/$post->id": route("login") }}" class="btn btn-primary">Read More &rarr;</a>
                               @auth
                                    @if(auth()->user()->is_admin == 1)
                                        <a class='btn btn-warning pull-right text-white' href='{{ route("post.edit",$post->id) }}' data-id="{{$post->id}}">Edit</a>
                                        <a class='deletePostButton btn btn-danger pull-right text-white' data-id="{{$post->id}}">Delete</a>
                                    @endif
                                @endauth
                            </div>
                            <div class="card-footer text-muted">
                                Posted on {{ $post->created_at->toFormattedDateString() }} by
                                <a href="#">{{ ucfirst($post->user->name) }}</a>

                            </div>
                    </div>
                     @empty
                     <h1>No Posts Available</h1>
                @endforelse

                {{--<!-- Pagination -->--}}
                <div class="pagination justify-content-center mb-4">
                    {{ $posts->links() }}
                </div>

            </div>

            <!-- Sidebar Widgets Column -->
            {{-- Note this coloumn will only be shown if the user is logged in --}}
            <div class="col-md-4 {{ Auth::check() ? "" : "d-none"}}">

                <!-- Search Widget -->
                {{--<div class="card my-4">--}}
                    {{--<h5 class="card-header">Search</h5>--}}
                    {{--<div class="card-body">--}}
                        {{--<div class="input-group">--}}
                            {{--<input type="text" class="form-control" placeholder="Search for...">--}}
                            {{--<span class="input-group-btn">--}}
                  {{--<button class="btn btn-secondary" type="button">Go!</button>--}}
                {{--</span>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</div>--}}

            {{-- Including tags widget--}}
            @include("includes.frontend.tags-widget")

                <!-- Side Widget -->
                {{--<div class="card my-4">--}}
                    {{--<h5 class="card-header">Side Widget</h5>--}}
                    {{--<div class="card-body">--}}
                        {{--You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!--}}
                    {{--</div>--}}
                {{--</div>--}}
            </div>
        </div>
    </div>
    {{-- Footer --}}
    <footer class="py-3 bg-dark bottom">
        {{--class = fixed-bottom--}}
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Technical Test 2018</p>
        </div>
    </footer>
@endsection

resources/views/posts/show.blade.php
<?php
// an array of colors
$badgeColors = ["primary", "secondary", "success", "danger", "warning", "info", "dark"]
?>
{{-- Extending the frontend layout--}}
@extends("layouts.frontend.layout")

{{-- This page is responsible to show posts on the home page--}}

{{-- This section is for page title--}}
@section("title")
    Post Details
@endsection

@section("main-container")
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="{{ Auth::check() ? "col-md-8" : "col-md-12"}}">

            {{--<h1 class="my-4">Page Heading--}}
            {{--<small>Secondary Text</small>--}}
            {{--</h1>--}}

            <!-- Blog Post -->
                    <div class="card mb-4 mt-4">
                        {{--if the user is logged in then the display size of image will be 750x300
                            else it will be 1050x300--}}
                        {{--http://placehold.it/{{ Auth::check() ? "750x300" : "1050x300--}}
                        <img class="card-img-top" src="{{ asset("assets/frontend/images/post/".$post->image) }}"
                             alt="Card image cap" width="300" height="350">
                        <div class="card-body">
                            <h2 class="card-title">{{ $post->title }}</h2>
                            {{-- This will only be shown if the user is logged in--}}
                            @if(auth::check())
                                {{-- This loop will fetch all the tags linked with the post--}}
                                @foreach($post->tags as $tag)
                                    {{-- The badgeColors array will work from index 0 to the size of array -1 --}}
                                    <span class="badge badge-pill badge-{{ $badgeColors[mt_rand(0,sizeof($badgeColors)-1)] }}">{{ $tag->name }}</span>
                                @endforeach
                            @endif
                            {{-- This will only be shown if the user is logged in--}}
                            @if(auth::check())
                                <p class="card-text">{{ $post->description }}</p>
                            @endif
                        </div>
                        <div class="card-footer text-muted">
                            Posted on {{ $post->created_at->toFormattedDateString() }} by
                            <a href="#">{{ ucfirst($post->user->name) }}</a>
                        </div>
                    </div>


                {{--<!-- Pagination -->--}}
                {{--<div class="pagination justify-content-center mb-4">--}}
                    {{--{{ $posts->links() }}--}}
                {{--</div>--}}

            </div>

            <!-- Sidebar Widgets Column -->
            {{-- Note this coloumn will only be shown if the user is logged in --}}
            <div class="col-md-4 {{ Auth::check() ? "" : "d-none"}}">

                <!-- Search Widget -->
            {{--<div class="card my-4">--}}
            {{--<h5 class="card-header">Search</h5>--}}
            {{--<div class="card-body">--}}
            {{--<div class="input-group">--}}
            {{--<input type="text" class="form-control" placeholder="Search for...">--}}
            {{--<span class="input-group-btn">--}}
            {{--<button class="btn btn-secondary" type="button">Go!</button>--}}
            {{--</span>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}

            {{-- Including tags widget--}}
            @include("includes.frontend.tags-widget")

            <!-- Side Widget -->
                {{--<div class="card my-4">--}}
                {{--<h5 class="card-header">Side Widget</h5>--}}
                {{--<div class="card-body">--}}
                {{--You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!--}}
                {{--</div>--}}
                {{--</div>--}}

            </div>
        </div>
    </div>
@endsection