routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Route::get('/home,/', 'HomeController@home')->name('home');

// Main page
Route::get('/', 'HomeController@home')->name('home');
// Routes for UserController
Route::resource('/user', 'UserController');
// Routes for PostController
Route::resource('/post', 'PostController');
// Routes for TagController
Route::resource('/tag', 'TagController');

resources/views/includes/frontend/footer.blade.php
<!-- Footer -->
{{--<footer class="py-3 bg-dark bottom">--}}
    {{--class = fixed-bottom--}}
    {{--<div class="container">--}}
        {{--<p class="m-0 text-center text-white">Copyright &copy; Technical Test 2018</p>--}}
    {{--</div>--}}
{{--</footer>--}}

resources/views/includes/frontend/nav-links.blade.php
{{--this file is for the links in navbar--}}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{route("home")}}">{{ "Technical Test" }}</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            {{-- This will work only if the user is looged in--}}
            @auth
                {{-- These links will only be shown if the logged in user is admin --}}
                <ul class="nav navbar-nav {{ Auth::user()->is_admin == 1 ? "" : "d-none"}}">
                    <li class="nav-item {{ Request::is("post/create") ? "active" : "" }}">
                        <a class="nav-link" href="{{ route("post.create") }}">Posts</a>
                    </li>
                    <li class="nav-item {{ Request::is("tag") ? "active" : "" }}">
                        <a class="nav-link" href="{{ route("tag.index") }}">Tags</a>
                    </li>
                </ul>
            @endauth
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item {{ Request::is("/") ? "active" : "" }}">
                        <a class="nav-link" href="{{ route('home') }}">Home</a>
                    </li>
                    <li class="nav-item {{ Request::is("login") ? "active" : "" }}">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    <li class="nav-item {{ Request::is("register") ? "active" : "" }}">
                        @if (Route::has('register'))
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        @endif
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ ucfirst(Auth::user()->name) }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                                 document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/includes/frontend/tags-widget.blade.php
<!-- Tags Widget -->
<div class="card my-4">
    <h5 class="card-header">Tags</h5>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                {{--<ul class="mb-0">--}}
                @foreach($tags as $tag)
                    <li class="list-inline-item col-sm-5">
                        <a href="/tag/{{$tag->id}}">{{ ucfirst($tag->name) }}</a>
                    </li>
                @endforeach
                {{--</ul>--}}
            </div>
        </div>
    </div>
</div>